package com.apklachy.app.util

object Marcas {

    val TODAS: List<String> = listOf(
        "Alcatel",
        "Apple",
        "Asus",
        "BlackBerry",
        "BLU",
        "BQ",
        "Coolpad",
        "Crosscall",
        "Cubot",
        "Doogee",
        "Essential",
        "Fairphone",
        "Gigaset",
        "Google",
        "Hisense",
        "Honor",
        "HTC",
        "Huawei",
        "Infinix",
        "Itel",
        "iQOO",
        "Kodak",
        "Lanix",
        "Lenovo",
        "LG",
        "Maxwest",
        "Meizu",
        "Micromax",
        "Microsoft",
        "Motorola",
        "Multilaser",
        "Nokia",
        "Nothing",
        "Nubia",
        "OnePlus",
        "Oppo",
        "Oukitel",
        "Positivo",
        "Realme",
        "Samsung",
        "Sharp",
        "Sony",
        "TCL",
        "Tecno",
        "Ulefone",
        "Umidigi",
        "Vivo",
        "Vodafone",
        "Wiko",
        "Xiaomi",
        "Zonda",
        "ZTE"
    )

    val POPULARES: List<String> = listOf(
        "Samsung",
        "Apple",
        "Xiaomi",
        "Huawei",
        "Motorola",
        "LG",
        "Nokia",
        "Oppo",
        "Vivo",
        "Realme",
        "Honor",
        "ZTE"
    )
}
